<a href="https://colab.research.google.com/github/2017710206255MN/Machine-Learning/blob/main/Week_2_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 

In [2]:
array = np.array([1,2,3,4,5]) # creating
print(array)

[1 2 3 4 5]


In [3]:
array2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]) # shape of array
print(array2.shape) 

(15,)


In [4]:
array3 = array2.reshape(3,5) # reshape the array,we have to save new variable becasue it is temporary.
print(array3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [6]:
print("shape: ",array3.shape) #(3, 5)

print("dimension: ",array3.ndim) #dimension:  2

print("data type: ",array3.dtype.name) #data type:  int32

print("size: ",array3.size) #size:  15, shape before reshape
                       
print("type",type(array3))  #type <class 'numpy.ndarray'>

shape:  (3, 5)
dimension:  2
data type:  int64
size:  15
type <class 'numpy.ndarray'>


In [7]:
array3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) #reshape dimension without using reshape method.

In [8]:
print(array3) #array([[ 1,  2,  3,  4],
                     #[ 5,  6,  7,  8],
                     #[ 9, 10, 11, 12]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
print(array3.shape) #(3, 4)

(3, 4)


In [12]:
zeros= np.zeros((3,4)) #3 rows and 4 columns zero array

In [13]:
zeros[0,0]=5
print(zeros)

[[5. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
np.ones((3,4)) #1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.empty((4,5)) #emphty

array([[0. , 0. , 0.3, 1. , 0. ],
       [0. , 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 0. , 0. ],
       [1. , 0.5, 0. , 0. , 1. ]])

In [18]:
np.arange(10,50,5) #creates an array with between 10 and 50 numbers and step size 5

array([10, 15, 20, 25, 30, 35, 40, 45])

In [19]:
a= np.linspace(0,10,20) #20 numbers between 0 and 10 are printed.
#array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
#       2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
#       5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
#       7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])
print(a)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [28]:
#numpy basic operations
a = np.array([1,2,3])
b = np.array([4,5,6]) 

print(a+b) #[5 7 9]
print(a**2) #[1 4 9]

[5 7 9]
[1 4 9]


In [23]:
a = np.array([1,2,3,4,5,6,7]) #vektor -> dimension 1

In [29]:
list_ = [1,2,3,4]
array = np.array([5,6,7,8])
print(list_)
print(array)

[1, 2, 3, 4]
[5 6 7 8]


In [33]:
array = np.array(list_) #convert list to array
print(array)

[1 2 3 4]


In [37]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [38]:
b=a

c=a

b[0]=5 
print(a,b,c) # in the same memory area

[5 2 3] [5 2 3] [5 2 3]


In [39]:
d = a.copy() # different memeory area

In [40]:
a = np.array([1,2,3,4,5,6,7]) #vector -> dimension 1
print(a)

[1 2 3 4 5 6 7]


In [41]:
print(a[0]) 

1


In [ ]:
print(a[0:4]) # 0-4 elmenets

[1 2 3 4]


In [42]:
reverse_array = a[::-1] #reverse array.
print(reverse_array)

[7 6 5 4 3 2 1]


In [43]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]]) 
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [46]:
print(b[1,1]) #1st row and first column value

print(b[:,1]) #all rows but second column. [2 7]

print(b[1,:]) #second row. [ 6  7  8  9 10]

print(b[1,1:4]) #2.row  2. 3. 4. columns. [7 8 9]

print(b[-1,:]) #last row and all colums. [ 6  7  8  9 10]

print(b[:,-1]) #last columns and all rows. [ 5 10]

7
[2 7]
[ 6  7  8  9 10]
[7 8 9]
[ 6  7  8  9 10]
[ 5 10]


In [47]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]]) #3*3 array.
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
a = array.ravel() #convert to one dimension.
print(a)

[1 2 3 4 5 6 7 8 9]


In [49]:
array2 = a.reshape(3,3) #again 3*3 array.
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
array_transpose = array2.T #transpose of array
                           #array([[1, 4, 7],
                                  #[2, 5, 8],
                                  #[3, 6, 9]])
print(array_transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [52]:
array3 = np.array([[1,2],[3,4],[5,6]])
print(array3)

[[1 2]
 [3 4]
 [5 6]]


In [53]:
array3.resize((2,3)) #change dimension of array, permenantly
print(array3)

[[1 2 3]
 [4 5 6]]
